spring:
  profiles:
    include: ${FS_SYSTEM_NAME:local-int}

DYNAMODB_TABLE_NAME: ps-dynamodb-spring-boot-microbadge

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: INFO
      hibernate: WARN
      apache:
        commons:
          dbcp2: DEBUG

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html
management:
  security:
    enabled: false
  port: 9000

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
endpoints:
  enabled: false
  health:
    enabled: true
    path: /healthcheck/heartbeat
  metrics:
    enabled: true
  info:
    enabled: true

info:
   app:
     name: @project.artifactId@
     description: @project.description@
     version: @project.version@


---

spring:
  profiles: local-int

dynamo:
  db: local

url:
  base: http://integration.familysearch.org
